/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import main.index;
import backpro.backpro;
import Data.Data;
import javax.swing.JOptionPane;
import resizeImage.resizeImage;
import model.model_emas;
import model.model_data_train;
import model.model_data_test;
import model.model_pelatihan;
import model.model_pengujian;
import model.model_report;
import diagram.garis;
import diagram.batang;

/**
 *
 * @author Wahyu Imam
 */
public class utama extends javax.swing.JFrame {
    index main = new index();
    backpro bp = new backpro();
    Data data = new Data();
    resizeImage resizeImage = new resizeImage();
    model_emas modelUtama = new model_emas();
    model_data_train modelDataTrain = new model_data_train();
    model_data_test modelDataTest = new model_data_test();
    model_pelatihan modelPelatihan = new model_pelatihan();
    model_pengujian modelPengujian = new model_pengujian();
    model_report modelReport = new model_report();
    garis g = new garis();
    batang b = new batang();
    
    public DefaultTableModel modelTbEmas;
    public DefaultTableModel modelTbDataLatih;
    public DefaultTableModel modelTbDataTest;
    public DefaultTableModel modelTbReport;
    String[] headerTbEmas = {"No","Tanggal","Harga"};
    String[] headerTbDataLatih = {"No","Tanggal","Harga"};
    String[] headerTbDataTest = {"No","Tanggal","Harga"};
    String[] headerTbReport = {"No", "Input Layer", "Node Hidden", "Maks Iterasi", "Target Error", 
        "KB", "Jarak Output", "Tgl Awal Data Train", "Tgl Akhir Data Train", "Jml Data Train", 
        "Epoch terakhir", "Error Terakhir", "Tgl Awal Data Test", "Tgl Akhir Data Test", 
        "Jml Data Test", "Error"};
    String[] headerTbReport2 = {"No", "Input Layer", "Node Hidden", "Maks Iterasi", "Target Error", 
        "KB", "Jarak Output", "Error"};
    // VARIABEL DATA TRAIN
    String tglTrainDari, tglTrainSampai;
    
    // VARIABEL DATA TEST
    String tglTestDari, tglTestSampai;
    
    // VARIABEL PENGUJIAN
    double[] dataTestOut, actual;
    
    /**
     * Creates new form utama
     */
    public utama() {
        initComponents();
        awal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBackground = new javax.swing.JPanel();
        pHeader = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        lbTitleProject = new javax.swing.JLabel();
        pFooter = new javax.swing.JPanel();
        lbFooterCreator = new javax.swing.JLabel();
        lbFooterVersi = new javax.swing.JLabel();
        lbFooterTgl = new javax.swing.JLabel();
        pMenu = new javax.swing.JPanel();
        lbMenu = new javax.swing.JLabel();
        pMenuBeranda = new javax.swing.JPanel();
        lbIconMenuBeranda = new javax.swing.JLabel();
        lbMenuBeranda = new javax.swing.JLabel();
        pMenuEmas = new javax.swing.JPanel();
        lbMenuEmas = new javax.swing.JLabel();
        lbIconMenuEmas = new javax.swing.JLabel();
        pMenuDataLatihUji = new javax.swing.JPanel();
        lbIconMenuDataLatihUji = new javax.swing.JLabel();
        lbMenuDataLatihUji = new javax.swing.JLabel();
        pMenuPelatihan = new javax.swing.JPanel();
        lbIconMenuPelatihan = new javax.swing.JLabel();
        lbMenuPelatihan = new javax.swing.JLabel();
        pMenuPengujian = new javax.swing.JPanel();
        lbIconMenuPengujian = new javax.swing.JLabel();
        lbMenuPengujian = new javax.swing.JLabel();
        pMenuReport = new javax.swing.JPanel();
        lbIconMenuRiwayat = new javax.swing.JLabel();
        lbMenuReport = new javax.swing.JLabel();
        lbIconPath = new javax.swing.JLabel();
        lbPath = new javax.swing.JLabel();
        pTengah = new javax.swing.JPanel();
        pBeranda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pEmas = new javax.swing.JPanel();
        pTambahEmas = new javax.swing.JPanel();
        lbInputEmas = new javax.swing.JLabel();
        lbInputTanggal = new javax.swing.JLabel();
        txtTgl = new javax.swing.JTextField();
        lbInputHarga = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmas = new javax.swing.JTable();
        lbJmlDataEmas = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        pDataLatihUji = new javax.swing.JPanel();
        pDataTrain = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dcLatihDari = new com.toedter.calendar.JDateChooser();
        dcLatihSampai = new com.toedter.calendar.JDateChooser();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbDataLatih = new javax.swing.JTable();
        lbJmlDataTrain = new javax.swing.JLabel();
        btnSimpanDataLatih = new javax.swing.JButton();
        pdataTest = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dcUjiDari = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        dcUjiSampai = new com.toedter.calendar.JDateChooser();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbdataUji = new javax.swing.JTable();
        lbJmlDataTest = new javax.swing.JLabel();
        btnSimpanDataUji = new javax.swing.JButton();
        pPelatihan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPelatihan = new javax.swing.JTable();
        pParameterJST = new javax.swing.JPanel();
        lbParameterJST = new javax.swing.JLabel();
        lbInputLayer = new javax.swing.JLabel();
        txtInputLayer = new javax.swing.JTextField();
        lbNodeHiddenLayer = new javax.swing.JLabel();
        txtNodeHiddenLayer = new javax.swing.JTextField();
        lbMaxIterasi = new javax.swing.JLabel();
        txtMaxIterasi = new javax.swing.JTextField();
        lbTargetError = new javax.swing.JLabel();
        txtTargerError = new javax.swing.JTextField();
        lbKonstantaBelajar = new javax.swing.JLabel();
        txtKonstantaBelajar = new javax.swing.JTextField();
        btnProsesPalatihan = new javax.swing.JButton();
        lbJarakDataOut = new javax.swing.JLabel();
        txtJarakDataOut = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtHasilPelatihan = new javax.swing.JTextArea();
        lbPelatihanJmlDataTrain = new javax.swing.JLabel();
        btnTampilBobotTrain = new javax.swing.JButton();
        lbNorDenorPelatihan = new javax.swing.JLabel();
        btnTampilGraikError = new javax.swing.JButton();
        pPengujian = new javax.swing.JPanel();
        pParameterJSTUji = new javax.swing.JPanel();
        lbParameterJSTUji = new javax.swing.JLabel();
        lbInputLayerUji = new javax.swing.JLabel();
        txtInputLayerUji = new javax.swing.JTextField();
        lbNodeHiddenLayerUji = new javax.swing.JLabel();
        txtNodeHiddenLayerUji = new javax.swing.JTextField();
        btnProsesUji = new javax.swing.JButton();
        lbJarakDataOutUji = new javax.swing.JLabel();
        txtJarakDataOutUji = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbPengujian = new javax.swing.JTable();
        lbNorDenorPengujian = new javax.swing.JLabel();
        lbPengujianJmlDataTest = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtHasilPengujian = new javax.swing.JTextArea();
        btnSimpanPengujian = new javax.swing.JButton();
        btnTampilHasilActual = new javax.swing.JButton();
        btntampilBobotPengujian = new javax.swing.JButton();
        btnTampilGrafikPerbandingan = new javax.swing.JButton();
        pReport = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbReport = new javax.swing.JTable();
        lbInfoErrorTerkecil = new javax.swing.JLabel();
        btnGratikPerbandinganMinError = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pBackground.setBackground(new java.awt.Color(233, 236, 242));
        pBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pHeader.setBackground(new java.awt.Color(72, 78, 84));
        pHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(153, 153, 153)));
        pHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(new java.awt.Color(173, 9, 0));
        btnExit.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("X");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pHeader.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1316, 0, 50, 30));

        lbTitleProject.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        lbTitleProject.setForeground(new java.awt.Color(255, 255, 255));
        lbTitleProject.setText("Aplikasi Prediksi Harga Emas");
        pHeader.add(lbTitleProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 30));

        pBackground.add(pHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 30));

        pFooter.setBackground(new java.awt.Color(72, 78, 84));
        pFooter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        pFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbFooterCreator.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbFooterCreator.setForeground(new java.awt.Color(255, 255, 255));
        lbFooterCreator.setText("M W I @ 2020");
        pFooter.add(lbFooterCreator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 20));

        lbFooterVersi.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbFooterVersi.setForeground(new java.awt.Color(255, 255, 255));
        lbFooterVersi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbFooterVersi.setText("versi 1.0.0 ");
        pFooter.add(lbFooterVersi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 130, 20));

        lbFooterTgl.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbFooterTgl.setForeground(new java.awt.Color(255, 255, 255));
        lbFooterTgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFooterTgl.setText("tgl");
        pFooter.add(lbFooterTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 20));

        pBackground.add(pFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 718, 1370, 20));

        pMenu.setBackground(new java.awt.Color(33, 79, 80));
        pMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMenu.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        lbMenu.setForeground(new java.awt.Color(255, 255, 255));
        lbMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenu.setText("M E N U");
        lbMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pMenu.add(lbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, 40));

        pMenuBeranda.setBackground(new java.awt.Color(33, 79, 80));
        pMenuBeranda.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        pMenuBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pMenuBeranda.add(lbIconMenuBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 20, 20));

        lbMenuBeranda.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        lbMenuBeranda.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuBeranda.setText("Beranda");
        lbMenuBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuBerandaMouseClicked(evt);
            }
        });
        pMenuBeranda.add(lbMenuBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, -1));

        pMenu.add(pMenuBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 120, 216, 60));

        pMenuEmas.setBackground(new java.awt.Color(33, 79, 80));
        pMenuEmas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        pMenuEmas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMenuEmas.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        lbMenuEmas.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuEmas.setText("Emas");
        lbMenuEmas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuEmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuEmasMouseClicked(evt);
            }
        });
        pMenuEmas.add(lbMenuEmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));
        pMenuEmas.add(lbIconMenuEmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 20, 20));

        pMenu.add(pMenuEmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 179, 216, 60));

        pMenuDataLatihUji.setBackground(new java.awt.Color(33, 79, 80));
        pMenuDataLatihUji.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        pMenuDataLatihUji.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pMenuDataLatihUji.add(lbIconMenuDataLatihUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 20, 20));

        lbMenuDataLatihUji.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        lbMenuDataLatihUji.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuDataLatihUji.setText("Data Latih dan Uji");
        lbMenuDataLatihUji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuDataLatihUji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuDataLatihUjiMouseClicked(evt);
            }
        });
        pMenuDataLatihUji.add(lbMenuDataLatihUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 20));

        pMenu.add(pMenuDataLatihUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 238, 216, 60));

        pMenuPelatihan.setBackground(new java.awt.Color(33, 79, 80));
        pMenuPelatihan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        pMenuPelatihan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pMenuPelatihan.add(lbIconMenuPelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 20, 20));

        lbMenuPelatihan.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        lbMenuPelatihan.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuPelatihan.setText("Pelatihan");
        lbMenuPelatihan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuPelatihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuPelatihanMouseClicked(evt);
            }
        });
        pMenuPelatihan.add(lbMenuPelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 20));

        pMenu.add(pMenuPelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 297, 216, 60));

        pMenuPengujian.setBackground(new java.awt.Color(33, 79, 80));
        pMenuPengujian.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        pMenuPengujian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pMenuPengujian.add(lbIconMenuPengujian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 20, 20));

        lbMenuPengujian.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        lbMenuPengujian.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuPengujian.setText("Pengujian");
        lbMenuPengujian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuPengujian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuPengujianMouseClicked(evt);
            }
        });
        pMenuPengujian.add(lbMenuPengujian, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        pMenu.add(pMenuPengujian, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 356, 216, 60));

        pMenuReport.setBackground(new java.awt.Color(33, 79, 80));
        pMenuReport.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(51, 51, 51)));
        pMenuReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pMenuReport.add(lbIconMenuRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 20, 20));

        lbMenuReport.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        lbMenuReport.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuReport.setText("Riwayat");
        lbMenuReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuReportMouseClicked(evt);
            }
        });
        pMenuReport.add(lbMenuReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 20));

        pMenu.add(pMenuReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 415, 216, 60));

        pBackground.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 29, 220, 690));
        pBackground.add(lbIconPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 15, 15));

        lbPath.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lbPath.setText("/ Beranda");
        pBackground.add(lbPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 38, 240, 20));

        pTengah.setBackground(new java.awt.Color(241, 244, 247));
        pTengah.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(153, 153, 153)));
        pTengah.setLayout(new java.awt.CardLayout());

        pBeranda.setBackground(new java.awt.Color(241, 244, 247));
        pBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang");
        pBeranda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 420, -1));

        pTengah.add(pBeranda, "card2");

        pEmas.setBackground(new java.awt.Color(241, 244, 247));
        pEmas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pTambahEmas.setBackground(new java.awt.Color(241, 244, 247));
        pTambahEmas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pTambahEmas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbInputEmas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lbInputEmas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInputEmas.setText("Tambah");
        lbInputEmas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pTambahEmas.add(lbInputEmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 120, 40));

        lbInputTanggal.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbInputTanggal.setText("Tanggal :");
        pTambahEmas.add(lbInputTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtTgl.setEditable(false);
        txtTgl.setBackground(new java.awt.Color(241, 244, 247));
        txtTgl.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtTgl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        pTambahEmas.add(txtTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 260, 30));

        lbInputHarga.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbInputHarga.setText("Harga :");
        pTambahEmas.add(lbInputHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtHarga.setBackground(new java.awt.Color(241, 244, 247));
        txtHarga.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtHarga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        pTambahEmas.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 260, 30));

        btnSimpan.setBackground(new java.awt.Color(225, 225, 225));
        btnSimpan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        pTambahEmas.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 90, 40));

        pEmas.add(pTambahEmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 300, 530));

        tbEmas.setFont(new java.awt.Font("Ebrima", 0, 13)); // NOI18N
        tbEmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEmas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbEmas.setRowHeight(20);
        jScrollPane1.setViewportView(tbEmas);

        pEmas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 820, 530));

        lbJmlDataEmas.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbJmlDataEmas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbJmlDataEmas.setText("0");
        pEmas.add(lbJmlDataEmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, 320, -1));

        btnUbah.setBackground(new java.awt.Color(225, 225, 225));
        btnUbah.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        pEmas.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 100, 40));

        btnHapus.setBackground(new java.awt.Color(225, 225, 225));
        btnHapus.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        pEmas.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 90, 40));

        pTengah.add(pEmas, "card3");

        pDataLatihUji.setBackground(new java.awt.Color(241, 244, 247));
        pDataLatihUji.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pDataTrain.setBackground(new java.awt.Color(241, 244, 247));
        pDataTrain.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Data Latih", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 0, 14))); // NOI18N
        pDataTrain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(241, 244, 247));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Tanggal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel4.setText("Dari :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel5.setText("Sampai :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 30));

        dcLatihDari.setDateFormatString("yyyy-MM-dd");
        dcLatihDari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcLatihDariPropertyChange(evt);
            }
        });
        jPanel3.add(dcLatihDari, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 30));

        dcLatihSampai.setDateFormatString("yyyy-MM-dd");
        dcLatihSampai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcLatihSampaiPropertyChange(evt);
            }
        });
        jPanel3.add(dcLatihSampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 180, 30));

        pDataTrain.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 520, 80));

        tbDataLatih.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tbDataLatih.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDataLatih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbDataLatih.setRowHeight(20);
        jScrollPane4.setViewportView(tbDataLatih);

        pDataTrain.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 520, 420));

        lbJmlDataTrain.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbJmlDataTrain.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbJmlDataTrain.setText("0");
        pDataTrain.add(lbJmlDataTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 260, -1));

        btnSimpanDataLatih.setBackground(new java.awt.Color(225, 225, 225));
        btnSimpanDataLatih.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSimpanDataLatih.setText("Simpan");
        btnSimpanDataLatih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpanDataLatih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanDataLatihActionPerformed(evt);
            }
        });
        pDataTrain.add(btnSimpanDataLatih, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 120, 40));

        pDataLatihUji.add(pDataTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 540, 600));

        pdataTest.setBackground(new java.awt.Color(241, 244, 247));
        pdataTest.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Data Uji", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 0, 14))); // NOI18N
        pdataTest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(241, 244, 247));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Tanggal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 0, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel7.setText("Dari :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        dcUjiDari.setDateFormatString("yyyy-MM-dd");
        dcUjiDari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcUjiDariPropertyChange(evt);
            }
        });
        jPanel4.add(dcUjiDari, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 30));

        jLabel8.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel8.setText("Sampai :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 30));

        dcUjiSampai.setDateFormatString("yyyy-MM-dd");
        dcUjiSampai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcUjiSampaiPropertyChange(evt);
            }
        });
        jPanel4.add(dcUjiSampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 180, 30));

        pdataTest.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 530, 80));

        tbdataUji.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tbdataUji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbdataUji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbdataUji.setRowHeight(20);
        jScrollPane5.setViewportView(tbdataUji);

        pdataTest.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 530, 420));

        lbJmlDataTest.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbJmlDataTest.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbJmlDataTest.setText("0");
        pdataTest.add(lbJmlDataTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 300, -1));

        btnSimpanDataUji.setBackground(new java.awt.Color(225, 225, 225));
        btnSimpanDataUji.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSimpanDataUji.setText("Simpan");
        btnSimpanDataUji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpanDataUji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanDataUjiActionPerformed(evt);
            }
        });
        pdataTest.add(btnSimpanDataUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 120, 40));

        pDataLatihUji.add(pdataTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 550, 600));

        pTengah.add(pDataLatihUji, "card5");

        pPelatihan.setBackground(new java.awt.Color(241, 244, 247));
        pPelatihan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPelatihan.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tbPelatihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPelatihan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbPelatihan.setRowHeight(20);
        jScrollPane2.setViewportView(tbPelatihan);

        pPelatihan.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 500, 600));

        pParameterJST.setBackground(new java.awt.Color(241, 244, 247));
        pParameterJST.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pParameterJST.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbParameterJST.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lbParameterJST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbParameterJST.setText("Parameter JST");
        lbParameterJST.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pParameterJST.add(lbParameterJST, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 150, 40));

        lbInputLayer.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbInputLayer.setText("Input Layer");
        pParameterJST.add(lbInputLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtInputLayer.setBackground(new java.awt.Color(241, 244, 247));
        txtInputLayer.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtInputLayer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtInputLayer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputLayerKeyReleased(evt);
            }
        });
        pParameterJST.add(txtInputLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 30));

        lbNodeHiddenLayer.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbNodeHiddenLayer.setText("Node Hidden Layer");
        pParameterJST.add(lbNodeHiddenLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtNodeHiddenLayer.setBackground(new java.awt.Color(241, 244, 247));
        txtNodeHiddenLayer.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtNodeHiddenLayer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtNodeHiddenLayer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNodeHiddenLayerKeyReleased(evt);
            }
        });
        pParameterJST.add(txtNodeHiddenLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 280, 30));

        lbMaxIterasi.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbMaxIterasi.setText("Max Iterasi");
        pParameterJST.add(lbMaxIterasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtMaxIterasi.setBackground(new java.awt.Color(241, 244, 247));
        txtMaxIterasi.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtMaxIterasi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        pParameterJST.add(txtMaxIterasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, 30));

        lbTargetError.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbTargetError.setText("Target Error");
        pParameterJST.add(lbTargetError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtTargerError.setBackground(new java.awt.Color(241, 244, 247));
        txtTargerError.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtTargerError.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        pParameterJST.add(txtTargerError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, 30));

        lbKonstantaBelajar.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbKonstantaBelajar.setText("Konstanta Belajar");
        pParameterJST.add(lbKonstantaBelajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtKonstantaBelajar.setBackground(new java.awt.Color(241, 244, 247));
        txtKonstantaBelajar.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtKonstantaBelajar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        pParameterJST.add(txtKonstantaBelajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 280, 30));

        btnProsesPalatihan.setBackground(new java.awt.Color(225, 225, 225));
        btnProsesPalatihan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnProsesPalatihan.setText("Proses");
        btnProsesPalatihan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProsesPalatihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesPalatihanActionPerformed(evt);
            }
        });
        pParameterJST.add(btnProsesPalatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 110, 40));

        lbJarakDataOut.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbJarakDataOut.setText("Jarak Data Output");
        pParameterJST.add(lbJarakDataOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        txtJarakDataOut.setBackground(new java.awt.Color(241, 244, 247));
        txtJarakDataOut.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtJarakDataOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtJarakDataOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJarakDataOutActionPerformed(evt);
            }
        });
        txtJarakDataOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJarakDataOutKeyReleased(evt);
            }
        });
        pParameterJST.add(txtJarakDataOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 280, 30));

        pPelatihan.add(pParameterJST, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 600));

        txtHasilPelatihan.setColumns(20);
        txtHasilPelatihan.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtHasilPelatihan.setLineWrap(true);
        txtHasilPelatihan.setRows(5);
        jScrollPane3.setViewportView(txtHasilPelatihan);

        pPelatihan.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 290, 500));

        lbPelatihanJmlDataTrain.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbPelatihanJmlDataTrain.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPelatihanJmlDataTrain.setText("0");
        pPelatihan.add(lbPelatihanJmlDataTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 350, -1));

        btnTampilBobotTrain.setBackground(new java.awt.Color(225, 225, 225));
        btnTampilBobotTrain.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnTampilBobotTrain.setText("Tampil Bobot");
        btnTampilBobotTrain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTampilBobotTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilBobotTrainActionPerformed(evt);
            }
        });
        pPelatihan.add(btnTampilBobotTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 290, 40));

        lbNorDenorPelatihan.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbNorDenorPelatihan.setText("Normalisasi");
        lbNorDenorPelatihan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNorDenorPelatihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNorDenorPelatihanMouseClicked(evt);
            }
        });
        pPelatihan.add(lbNorDenorPelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 100, -1));

        btnTampilGraikError.setBackground(new java.awt.Color(225, 225, 225));
        btnTampilGraikError.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnTampilGraikError.setText("Tampil Grafik Error");
        btnTampilGraikError.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTampilGraikError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilGraikErrorActionPerformed(evt);
            }
        });
        pPelatihan.add(btnTampilGraikError, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 290, 40));

        pTengah.add(pPelatihan, "card4");

        pPengujian.setBackground(new java.awt.Color(241, 244, 247));
        pPengujian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pParameterJSTUji.setBackground(new java.awt.Color(241, 244, 247));
        pParameterJSTUji.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pParameterJSTUji.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbParameterJSTUji.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lbParameterJSTUji.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbParameterJSTUji.setText("Parameter JST");
        lbParameterJSTUji.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pParameterJSTUji.add(lbParameterJSTUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 150, 40));

        lbInputLayerUji.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbInputLayerUji.setText("Input Layer");
        pParameterJSTUji.add(lbInputLayerUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtInputLayerUji.setEditable(false);
        txtInputLayerUji.setBackground(new java.awt.Color(241, 244, 247));
        txtInputLayerUji.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtInputLayerUji.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtInputLayerUji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputLayerUjiKeyReleased(evt);
            }
        });
        pParameterJSTUji.add(txtInputLayerUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 280, 30));

        lbNodeHiddenLayerUji.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbNodeHiddenLayerUji.setText("Node Hidden Layer");
        pParameterJSTUji.add(lbNodeHiddenLayerUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txtNodeHiddenLayerUji.setEditable(false);
        txtNodeHiddenLayerUji.setBackground(new java.awt.Color(241, 244, 247));
        txtNodeHiddenLayerUji.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtNodeHiddenLayerUji.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtNodeHiddenLayerUji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNodeHiddenLayerUjiKeyReleased(evt);
            }
        });
        pParameterJSTUji.add(txtNodeHiddenLayerUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 280, 30));

        btnProsesUji.setBackground(new java.awt.Color(225, 225, 225));
        btnProsesUji.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnProsesUji.setText("Proses");
        btnProsesUji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProsesUji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesUjiActionPerformed(evt);
            }
        });
        pParameterJSTUji.add(btnProsesUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 110, 40));

        lbJarakDataOutUji.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbJarakDataOutUji.setText("Jarak Data Output");
        pParameterJSTUji.add(lbJarakDataOutUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        txtJarakDataOutUji.setEditable(false);
        txtJarakDataOutUji.setBackground(new java.awt.Color(241, 244, 247));
        txtJarakDataOutUji.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtJarakDataOutUji.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtJarakDataOutUji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJarakDataOutUjiKeyReleased(evt);
            }
        });
        pParameterJSTUji.add(txtJarakDataOutUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 280, 30));

        pPengujian.add(pParameterJSTUji, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 600));

        tbPengujian.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tbPengujian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPengujian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbPengujian.setRowHeight(20);
        jScrollPane6.setViewportView(tbPengujian);

        pPengujian.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 500, 600));

        lbNorDenorPengujian.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbNorDenorPengujian.setText("Normalisasi");
        lbNorDenorPengujian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNorDenorPengujian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNorDenorPengujianMouseClicked(evt);
            }
        });
        pPengujian.add(lbNorDenorPengujian, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 100, -1));

        lbPengujianJmlDataTest.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbPengujianJmlDataTest.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPengujianJmlDataTest.setText("0");
        lbPengujianJmlDataTest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbPengujianJmlDataTestKeyReleased(evt);
            }
        });
        pPengujian.add(lbPengujianJmlDataTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 350, -1));

        txtHasilPengujian.setColumns(20);
        txtHasilPengujian.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        txtHasilPengujian.setLineWrap(true);
        txtHasilPengujian.setRows(5);
        jScrollPane7.setViewportView(txtHasilPengujian);

        pPengujian.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 290, 400));

        btnSimpanPengujian.setBackground(new java.awt.Color(225, 225, 225));
        btnSimpanPengujian.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSimpanPengujian.setText("Simpan Pengujian");
        btnSimpanPengujian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpanPengujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPengujianActionPerformed(evt);
            }
        });
        pPengujian.add(btnSimpanPengujian, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 290, 40));

        btnTampilHasilActual.setBackground(new java.awt.Color(225, 225, 225));
        btnTampilHasilActual.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnTampilHasilActual.setText("Tampil Hasil Actual Output");
        btnTampilHasilActual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTampilHasilActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilHasilActualActionPerformed(evt);
            }
        });
        pPengujian.add(btnTampilHasilActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 290, 40));

        btntampilBobotPengujian.setBackground(new java.awt.Color(225, 225, 225));
        btntampilBobotPengujian.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btntampilBobotPengujian.setText("Tampil Bobot");
        btntampilBobotPengujian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntampilBobotPengujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntampilBobotPengujianActionPerformed(evt);
            }
        });
        pPengujian.add(btntampilBobotPengujian, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 290, 40));

        btnTampilGrafikPerbandingan.setBackground(new java.awt.Color(225, 225, 225));
        btnTampilGrafikPerbandingan.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnTampilGrafikPerbandingan.setText("Tampil Grafik Perbandingan");
        btnTampilGrafikPerbandingan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTampilGrafikPerbandingan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilGrafikPerbandinganActionPerformed(evt);
            }
        });
        pPengujian.add(btnTampilGrafikPerbandingan, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 290, 40));

        pTengah.add(pPengujian, "card6");

        pReport.setBackground(new java.awt.Color(241, 244, 247));
        pReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 244, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbReport.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane8.setViewportView(tbReport);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1090, 520));

        pReport.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1110, 540));

        lbInfoErrorTerkecil.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        lbInfoErrorTerkecil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInfoErrorTerkecil.setText("jLabel2");
        pReport.add(lbInfoErrorTerkecil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 820, 20));

        btnGratikPerbandinganMinError.setBackground(new java.awt.Color(225, 225, 225));
        btnGratikPerbandinganMinError.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnGratikPerbandinganMinError.setText("Grafik Perbandingan Error Pengujian");
        btnGratikPerbandinganMinError.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGratikPerbandinganMinError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGratikPerbandinganMinErrorActionPerformed(evt);
            }
        });
        pReport.add(btnGratikPerbandinganMinError, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, 280, 40));

        pTengah.add(pReport, "card7");

        pBackground.add(pTengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 1150, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void awal(){
        lbTitleProject.requestFocus();
        lbFooterTgl.setText(main.getTglSekarang("dd - MMMM - yyyy"));
        showPanel(true, false, false, false, false, false);
        btnTampilBobotTrain.setEnabled(false);
        btnTampilGraikError.setEnabled(false);
        
        modelTbEmas = new DefaultTableModel(null, headerTbEmas);
        tbEmas.setModel(modelTbEmas);
        
        modelTbDataLatih = new DefaultTableModel(null, headerTbDataLatih);
        tbDataLatih.setModel(modelTbDataLatih);
        
        modelTbDataTest = new DefaultTableModel(null, headerTbDataTest);
        tbdataUji.setModel(modelTbDataTest);
        
        modelTbReport = new DefaultTableModel(null, headerTbReport2);
        tbReport.setModel(modelTbReport);
        
        modelUtama.tampil(this);
        lbJmlDataEmas.setText(String.valueOf("Jumlah Data Emas : "+main.formatUang(tbEmas.getRowCount())));
        txtTgl.setText(main.getTglSekarang("yyyy-MM-dd"));
    }
    
    private void showPanel(boolean pBeranda, boolean pEmas, boolean pData, boolean pPelatihan, 
            boolean pPengujian, boolean pReport){
        Color colorAsli = new Color(33,79,80);
        Color colorPilih = new Color(68, 106, 108);
        resizeImage.tampilImg(lbIconMenuBeranda, "/beranda/beranda putih.png");
        resizeImage.tampilImg(lbIconMenuEmas, "/emas/emas putih.png");
        resizeImage.tampilImg(lbIconMenuDataLatihUji, "/data/data putih.png");
        resizeImage.tampilImg(lbIconMenuPelatihan, "/ai/ai putih.png");
        resizeImage.tampilImg(lbIconMenuPengujian, "/ai/ai putih.png");
        resizeImage.tampilImg(lbIconMenuRiwayat, "/report/report putih.png");
        if(pBeranda){
            this.pBeranda.setVisible(true);
            this.pMenuBeranda.setBackground(colorPilih);
            resizeImage.tampilImg(lbIconPath, "/beranda/beranda hitam.png");
            lbPath.setText("/ "+lbMenuBeranda.getText());
        }else{
            this.pBeranda.setVisible(false);
            this.pMenuBeranda.setBackground(colorAsli);
        }
        
        if(pEmas){
            this.pEmas.setVisible(true);
            this.pMenuEmas.setBackground(colorPilih);
            resizeImage.tampilImg(lbIconPath, "/emas/emas hitam.png");
            lbPath.setText("/ "+lbMenuEmas.getText());
        }else{
            this.pEmas.setVisible(false);
            this.pMenuEmas.setBackground(colorAsli);
        }
        
        if(pData){
            this.pDataLatihUji.setVisible(true);
            this.pMenuDataLatihUji.setBackground(colorPilih);
            resizeImage.tampilImg(lbIconPath, "/data/data hitam.png");
            lbPath.setText("/ "+lbMenuDataLatihUji.getText());
        }else{
            this.pDataLatihUji.setVisible(false);
            this.pMenuDataLatihUji.setBackground(colorAsli);
        }
        
        if(pPelatihan){
            this.pPelatihan.setVisible(true);
            this.pMenuPelatihan.setBackground(colorPilih);
            resizeImage.tampilImg(lbIconPath, "/ai/ai hitam.png");
            lbPath.setText(" / "+lbMenuPelatihan.getText());
        }else{
            this.pPelatihan.setVisible(false);
            this.pMenuPelatihan.setBackground(colorAsli);
        }
        
        if(pPengujian){
            this.pPengujian.setVisible(true);
            this.pMenuPengujian.setBackground(colorPilih);
            resizeImage.tampilImg(lbIconPath, "/ai/ai hitam.png");
            lbPath.setText(" / "+lbMenuPengujian.getText());
        }else{
            this.pPengujian.setVisible(false);
            this.pMenuPengujian.setBackground(colorAsli);
        }
        
        if(pReport){
            this.pReport.setVisible(true);
            this.pMenuReport.setBackground(colorPilih);
            resizeImage.tampilImg(lbIconPath, "/report/report hitam.png");
            lbPath.setText(" / "+lbMenuReport.getText());
        }else{
            this.pReport.setVisible(false);
            this.pMenuReport.setBackground(colorAsli);
        }
    }
    
    // KOMPONEN EMAS
    
    public JTable getTbEmas() {
        return tbEmas;
    }

    public JLabel getLbIconMenuEmas() {
        return lbIconMenuEmas;
    }

    public JTextField getTxtHarga() {
        return txtHarga;
    }

    public JTextField getTxtTgl() {
        return txtTgl;
    }
    
    // KOMPONEN DATA TRAIN
    
    public JDateChooser getDcLatihDari() {
        return dcLatihDari;
    }

    public JDateChooser getDcLatihSampai() {
        return dcLatihSampai;
    }

    public JTable getTbDataLatih() {
        return tbDataLatih;
    }

    public String getTglTrainDari() {
        return tglTrainDari;
    }

    public String getTglTrainSampai() {
        return tglTrainSampai;
    }

    public JButton getBtnSimpanDataUji() {
        return btnSimpanDataUji;
    }
    
    // KOMPONEN DATA TEST
    
    public JDateChooser getDcUjiDari() {
        return dcUjiDari;
    }

    public JDateChooser getDcUjiSampai() {
        return dcUjiSampai;
    }

    public JTable getTbdataUji() {
        return tbdataUji;
    }

    public String getTglTestDari() {
        return tglTestDari;
    }

    public String getTglTestSampai() {
        return tglTestSampai;
    }
    
    // KOMPONEN PELATIHAN

    public JTable getTbPelatihan() {
        return tbPelatihan;
    }

    public JTextField getTxtInputLayer() {
        return txtInputLayer;
    }

    public JTextField getTxtJarakDataOut() {
        return txtJarakDataOut;
    }

    public JTextField getTxtKonstantaBelajar() {
        return txtKonstantaBelajar;
    }

    public JTextField getTxtMaxIterasi() {
        return txtMaxIterasi;
    }

    public JTextField getTxtNodeHiddenLayer() {
        return txtNodeHiddenLayer;
    }

    public JTextField getTxtTargerError() {
        return txtTargerError;
    }

    public JTextArea getTxtHasilPelatihan() {
        return txtHasilPelatihan;
    }
    
    // KOMPONEN PENGUJIAN
    
    public JTable getTbPengujian() {
        return tbPengujian;
    }

    public JTextArea getTxtHasilPengujian() {
        return txtHasilPengujian;
    }

    public JTextField getTxtInputLayerUji() {
        return txtInputLayerUji;
    }

    public JTextField getTxtJarakDataOutUji() {
        return txtJarakDataOutUji;
    }

    public JTextField getTxtNodeHiddenLayerUji() {
        return txtNodeHiddenLayerUji;
    }
    
    // KOMPONEN REPORT
    
    public JTable getTbReport() {
        return tbReport;
    }

    public JLabel getLbInfoErrorTerkecil() {
        return lbInfoErrorTerkecil;
    }
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void lbMenuBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuBerandaMouseClicked
        // TODO add your handling code here:
        showPanel(true, false, false, false, false, false);
    }//GEN-LAST:event_lbMenuBerandaMouseClicked

    private void lbMenuEmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuEmasMouseClicked
        // TODO add your handling code here:
        showPanel(false, true, false, false, false, false);
    }//GEN-LAST:event_lbMenuEmasMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(modelUtama.getKodeEmas(this) == null){
            modelUtama.simpan(this);
        }else{
            modelUtama.ubah(this);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void lbMenuPelatihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuPelatihanMouseClicked
        // TODO add your handling code here:
        showPanel(false, false, false, true, false, false);
    }//GEN-LAST:event_lbMenuPelatihanMouseClicked

    private void lbMenuDataLatihUjiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuDataLatihUjiMouseClicked
        // TODO add your handling code here:
        showPanel(false, false, true, false, false, false);
        modelDataTrain.setTglTrain(this);
        modelDataTrain.tampil(this);
        lbJmlDataTrain.setText(String.valueOf("Jumlah Data Train : "+main.formatUang(tbDataLatih.getRowCount())));
        
        modelDataTest.setTglTest(this);
        modelDataTest.tampil(this);
        lbJmlDataTest.setText(String.valueOf("Jumlah Data Test : "+main.formatUang(tbdataUji.getRowCount())));
    }//GEN-LAST:event_lbMenuDataLatihUjiMouseClicked

    private void dcLatihDariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcLatihDariPropertyChange
        // TODO add your handling code here:
        if (dcLatihDari.getDate() != null) {
            String patt = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(patt);
            tglTrainDari = String.valueOf(format.format(dcLatihDari.getDate()));
        }
    }//GEN-LAST:event_dcLatihDariPropertyChange

    private void dcLatihSampaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcLatihSampaiPropertyChange
        // TODO add your handling code here:
        if (dcLatihSampai.getDate() != null) {
            String patt = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(patt);
            tglTrainSampai = String.valueOf(format.format(dcLatihSampai.getDate()));
        }
    }//GEN-LAST:event_dcLatihSampaiPropertyChange

    private void dcUjiDariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcUjiDariPropertyChange
        // TODO add your handling code here:
        if (dcUjiDari.getDate() != null) {
            String patt = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(patt);
            tglTestDari = String.valueOf(format.format(dcUjiDari.getDate()));
        }
    }//GEN-LAST:event_dcUjiDariPropertyChange

    private void dcUjiSampaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcUjiSampaiPropertyChange
        // TODO add your handling code here:
        if (dcUjiSampai.getDate() != null) {
            String patt = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(patt);
            tglTestSampai = String.valueOf(format.format(dcUjiSampai.getDate()));
        }
    }//GEN-LAST:event_dcUjiSampaiPropertyChange

    private void btnSimpanDataLatihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanDataLatihActionPerformed
        // TODO add your handling code here:
        if(modelDataTrain.getKodeDataTrain() == null){
            modelDataTrain.simpan(this);
            lbJmlDataTrain.setText(String.valueOf("Jumlah Data Train : "+main.formatUang(tbDataLatih.getRowCount())));
        }else{
            modelDataTrain.ubah(this);
            lbJmlDataTrain.setText(String.valueOf("Jumlah Data Train : "+main.formatUang(tbDataLatih.getRowCount())));
        }
    }//GEN-LAST:event_btnSimpanDataLatihActionPerformed

    private void btnSimpanDataUjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanDataUjiActionPerformed
        // TODO add your handling code here:
        if(modelDataTest.getKodeDataTest() == null){
            modelDataTest.simpan(this);
            lbJmlDataTest.setText(String.valueOf("Jumlah Data Test : "+main.formatUang(tbdataUji.getRowCount())));
        }else{
            modelDataTest.ubah(this);
            lbJmlDataTest.setText(String.valueOf("Jumlah Data Test : "+main.formatUang(tbdataUji.getRowCount())));
        }
    }//GEN-LAST:event_btnSimpanDataUjiActionPerformed

    private void btnProsesPalatihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesPalatihanActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "mulai Pelatihan");
        double[][] dataTrain = modelPelatihan.dataTrain(this);
        String[] parameterJST = new String[3];
        parameterJST[0] = txtMaxIterasi.getText();
        parameterJST[1] = txtTargerError.getText();
        parameterJST[2] = txtKonstantaBelajar.getText();
        modelPelatihan.prosesTrain(this, dataTrain, parameterJST);
        btnTampilBobotTrain.setEnabled(true);
        btnTampilGraikError.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Selesai Pelatihan");
    }//GEN-LAST:event_btnProsesPalatihanActionPerformed

    private void txtInputLayerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputLayerKeyReleased
        // TODO add your handling code here:
        if(!txtInputLayer.getText().isEmpty() && !txtNodeHiddenLayer.getText().isEmpty() &&
                !txtJarakDataOut.getText().isEmpty()){
            double[][] dataTrain =  modelPelatihan.dataTrain(this);
            modelPelatihan.tampilDataTrain(this, dataTrain);
            lbPelatihanJmlDataTrain.setText(String.valueOf(main.formatUang(tbPelatihan.getRowCount())));
        }
    }//GEN-LAST:event_txtInputLayerKeyReleased

    private void txtNodeHiddenLayerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNodeHiddenLayerKeyReleased
        // TODO add your handling code here:
        if(!txtInputLayer.getText().isEmpty() && !txtNodeHiddenLayer.getText().isEmpty() &&
                !txtJarakDataOut.getText().isEmpty()){
            double[][] dataTrain =  modelPelatihan.dataTrain(this);
            modelPelatihan.tampilDataTrain(this, dataTrain);
            lbPelatihanJmlDataTrain.setText(String.valueOf(main.formatUang(tbPelatihan.getRowCount())));
        }
    }//GEN-LAST:event_txtNodeHiddenLayerKeyReleased

    private void txtJarakDataOutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJarakDataOutKeyReleased
        // TODO add your handling code here:
        if(!txtInputLayer.getText().isEmpty() && !txtNodeHiddenLayer.getText().isEmpty() &&
                !txtJarakDataOut.getText().isEmpty()){
            double[][] dataTrain =  modelPelatihan.dataTrain(this);
            modelPelatihan.tampilDataTrain(this, dataTrain);
            lbPelatihanJmlDataTrain.setText(String.valueOf(main.formatUang(tbPelatihan.getRowCount())));
        }
    }//GEN-LAST:event_txtJarakDataOutKeyReleased

    private void lbMenuPengujianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuPengujianMouseClicked
        // TODO add your handling code here:
        showPanel(false, false, false, false, true, false);
        modelPengujian.tampilParameter(this);
        double[][] dataTest = modelPengujian.dataTest(this);
        modelPengujian.tampilDataTest(this, dataTest);
        lbPengujianJmlDataTest.setText(String.valueOf(main.formatUang(tbPengujian.getRowCount())));
    }//GEN-LAST:event_lbMenuPengujianMouseClicked

    private void txtInputLayerUjiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputLayerUjiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputLayerUjiKeyReleased

    private void txtNodeHiddenLayerUjiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNodeHiddenLayerUjiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNodeHiddenLayerUjiKeyReleased

    private void btnProsesUjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesUjiActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Mulai pengujian");
        double[][] dataTest = modelPengujian.dataTest(this);
        double[][] norDataTest = bp.normaslisasi(dataTest);
        dataTestOut = data.dataOut(norDataTest);
        actual = modelPengujian.prosesPengujian(this, dataTest);
        JOptionPane.showMessageDialog(null, "Selesai pengujian");
    }//GEN-LAST:event_btnProsesUjiActionPerformed

    private void txtJarakDataOutUjiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJarakDataOutUjiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJarakDataOutUjiKeyReleased

    private void btnTampilBobotTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilBobotTrainActionPerformed
        // TODO add your handling code here:
        tampilBobot show = new tampilBobot(this, true, this);
        show.setVisible(true);
    }//GEN-LAST:event_btnTampilBobotTrainActionPerformed

    private void lbNorDenorPelatihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNorDenorPelatihanMouseClicked
        // TODO add your handling code here:
        double[][] dataTrain = modelPelatihan.dataTrain(this);
        if(lbNorDenorPelatihan.getText().equals("Normalisasi")){
            double[][] norDataTrain = bp.normaslisasi(dataTrain);
            modelPelatihan.tampilDataTrain(this, norDataTrain);
            lbNorDenorPelatihan.setText("Denormalisasi");
        }else{
            double[][] norDataTrain = bp.normaslisasi(dataTrain);
            double[][] denorDataTrain = bp.denorMasal(norDataTrain, dataTrain);
            modelPelatihan.tampilDataTrain(this, denorDataTrain);
            lbNorDenorPelatihan.setText("Normalisasi");
        }
    }//GEN-LAST:event_lbNorDenorPelatihanMouseClicked

    private void btntampilBobotPengujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntampilBobotPengujianActionPerformed
        // TODO add your handling code here:
        tampilBobot show = new tampilBobot(this, true, this);
        show.setVisible(true);
    }//GEN-LAST:event_btntampilBobotPengujianActionPerformed

    private void btnTampilHasilActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilHasilActualActionPerformed
        // TODO add your handling code here:
        double[][] dataTest = modelPengujian.dataTest(this);
        tampilHasilActualOut tampil = new tampilHasilActualOut(this, true, dataTest, actual);
        modelPengujian.tampilActual(tampil, dataTest, dataTestOut, actual);
        tampil.setVisible(true);
    }//GEN-LAST:event_btnTampilHasilActualActionPerformed

    private void lbPengujianJmlDataTestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbPengujianJmlDataTestKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbPengujianJmlDataTestKeyReleased

    private void lbNorDenorPengujianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNorDenorPengujianMouseClicked
        // TODO add your handling code here:
        double[][] dataTest = modelPengujian.dataTest(this);
        if(lbNorDenorPengujian.getText().equals("Normalisasi")){
            double[][] norDataTest = bp.normaslisasi(dataTest);
            modelPengujian.tampilDataTest(this, norDataTest);
            lbNorDenorPengujian.setText("Denormalisasi");
        }else{
            double[][] norDataTest = bp.normaslisasi(dataTest);
            double[][] denorDataTest = bp.denorMasal(norDataTest, dataTest);
            modelPengujian.tampilDataTest(this, denorDataTest);
            lbNorDenorPengujian.setText("Normalisasi");
        }
    }//GEN-LAST:event_lbNorDenorPengujianMouseClicked

    private void btnSimpanPengujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPengujianActionPerformed
        // TODO add your handling code here:
        if(txtHasilPengujian.getText() == null){
            JOptionPane.showMessageDialog(null, "Lakukan Pengjian Terlebih Dahulu");
        }else{
            modelPengujian.simpan(this);
        }
    }//GEN-LAST:event_btnSimpanPengujianActionPerformed

    private void lbMenuReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuReportMouseClicked
        // TODO add your handling code here:
        showPanel(false, false, false, false, false, true);
        modelReport.tampil(this);
    }//GEN-LAST:event_lbMenuReportMouseClicked

    private void btnTampilGrafikPerbandinganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilGrafikPerbandinganActionPerformed
        // TODO add your handling code here:
        g.garisTargetActual(dataTestOut, actual);
    }//GEN-LAST:event_btnTampilGrafikPerbandinganActionPerformed

    private void btnTampilGraikErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilGraikErrorActionPerformed
        // TODO add your handling code here:
        g.garisError(modelPelatihan.mse);
    }//GEN-LAST:event_btnTampilGraikErrorActionPerformed

    private void btnGratikPerbandinganMinErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGratikPerbandinganMinErrorActionPerformed
        // TODO add your handling code here:
        b.perBandinganOutput(b.data(b.jml()));
    }//GEN-LAST:event_btnGratikPerbandinganMinErrorActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        int baris = tbEmas.getSelectedRow();
        if(baris == -1){
            JOptionPane.showMessageDialog(null, "Pilih Data yang akan di ubah");
        }else{
            txtTgl.setText(tbEmas.getValueAt(baris, 1).toString());
            txtHarga.setText(tbEmas.getValueAt(baris, 2).toString());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int baris = tbEmas.getSelectedRow();
        if(baris == -1){
            JOptionPane.showMessageDialog(null, "Pilih Data yang akan di hapus");
        }else{
            modelUtama.hapus(this);
            txtTgl.setText(main.getTglSekarang("yyyy-MM-dd"));
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtJarakDataOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJarakDataOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJarakDataOutActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new utama().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGratikPerbandinganMinError;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnProsesPalatihan;
    private javax.swing.JButton btnProsesUji;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpanDataLatih;
    private javax.swing.JButton btnSimpanDataUji;
    private javax.swing.JButton btnSimpanPengujian;
    private javax.swing.JButton btnTampilBobotTrain;
    private javax.swing.JButton btnTampilGrafikPerbandingan;
    private javax.swing.JButton btnTampilGraikError;
    private javax.swing.JButton btnTampilHasilActual;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btntampilBobotPengujian;
    private com.toedter.calendar.JDateChooser dcLatihDari;
    private com.toedter.calendar.JDateChooser dcLatihSampai;
    private com.toedter.calendar.JDateChooser dcUjiDari;
    private com.toedter.calendar.JDateChooser dcUjiSampai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lbFooterCreator;
    private javax.swing.JLabel lbFooterTgl;
    private javax.swing.JLabel lbFooterVersi;
    private javax.swing.JLabel lbIconMenuBeranda;
    private javax.swing.JLabel lbIconMenuDataLatihUji;
    private javax.swing.JLabel lbIconMenuEmas;
    private javax.swing.JLabel lbIconMenuPelatihan;
    private javax.swing.JLabel lbIconMenuPengujian;
    private javax.swing.JLabel lbIconMenuRiwayat;
    private javax.swing.JLabel lbIconPath;
    private javax.swing.JLabel lbInfoErrorTerkecil;
    private javax.swing.JLabel lbInputEmas;
    private javax.swing.JLabel lbInputHarga;
    private javax.swing.JLabel lbInputLayer;
    private javax.swing.JLabel lbInputLayerUji;
    private javax.swing.JLabel lbInputTanggal;
    private javax.swing.JLabel lbJarakDataOut;
    private javax.swing.JLabel lbJarakDataOutUji;
    private javax.swing.JLabel lbJmlDataEmas;
    private javax.swing.JLabel lbJmlDataTest;
    private javax.swing.JLabel lbJmlDataTrain;
    private javax.swing.JLabel lbKonstantaBelajar;
    private javax.swing.JLabel lbMaxIterasi;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JLabel lbMenuBeranda;
    private javax.swing.JLabel lbMenuDataLatihUji;
    private javax.swing.JLabel lbMenuEmas;
    private javax.swing.JLabel lbMenuPelatihan;
    private javax.swing.JLabel lbMenuPengujian;
    private javax.swing.JLabel lbMenuReport;
    private javax.swing.JLabel lbNodeHiddenLayer;
    private javax.swing.JLabel lbNodeHiddenLayerUji;
    private javax.swing.JLabel lbNorDenorPelatihan;
    private javax.swing.JLabel lbNorDenorPengujian;
    private javax.swing.JLabel lbParameterJST;
    private javax.swing.JLabel lbParameterJSTUji;
    private javax.swing.JLabel lbPath;
    private javax.swing.JLabel lbPelatihanJmlDataTrain;
    private javax.swing.JLabel lbPengujianJmlDataTest;
    private javax.swing.JLabel lbTargetError;
    private javax.swing.JLabel lbTitleProject;
    private javax.swing.JPanel pBackground;
    private javax.swing.JPanel pBeranda;
    private javax.swing.JPanel pDataLatihUji;
    private javax.swing.JPanel pDataTrain;
    private javax.swing.JPanel pEmas;
    private javax.swing.JPanel pFooter;
    private javax.swing.JPanel pHeader;
    private javax.swing.JPanel pMenu;
    private javax.swing.JPanel pMenuBeranda;
    private javax.swing.JPanel pMenuDataLatihUji;
    private javax.swing.JPanel pMenuEmas;
    private javax.swing.JPanel pMenuPelatihan;
    private javax.swing.JPanel pMenuPengujian;
    private javax.swing.JPanel pMenuReport;
    private javax.swing.JPanel pParameterJST;
    private javax.swing.JPanel pParameterJSTUji;
    private javax.swing.JPanel pPelatihan;
    private javax.swing.JPanel pPengujian;
    private javax.swing.JPanel pReport;
    private javax.swing.JPanel pTambahEmas;
    private javax.swing.JPanel pTengah;
    private javax.swing.JPanel pdataTest;
    private javax.swing.JTable tbDataLatih;
    private javax.swing.JTable tbEmas;
    private javax.swing.JTable tbPelatihan;
    private javax.swing.JTable tbPengujian;
    private javax.swing.JTable tbReport;
    private javax.swing.JTable tbdataUji;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextArea txtHasilPelatihan;
    private javax.swing.JTextArea txtHasilPengujian;
    private javax.swing.JTextField txtInputLayer;
    private javax.swing.JTextField txtInputLayerUji;
    private javax.swing.JTextField txtJarakDataOut;
    private javax.swing.JTextField txtJarakDataOutUji;
    private javax.swing.JTextField txtKonstantaBelajar;
    private javax.swing.JTextField txtMaxIterasi;
    private javax.swing.JTextField txtNodeHiddenLayer;
    private javax.swing.JTextField txtNodeHiddenLayerUji;
    private javax.swing.JTextField txtTargerError;
    private javax.swing.JTextField txtTgl;
    // End of variables declaration//GEN-END:variables
}
